// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartnerGraph.Infrastructure.Persistence;

#nullable disable

namespace PartnerGraph.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PartnerGraphDbContext))]
    [Migration("20260923132425_AddPartnerGraphDomainModel")]
    partial class AddPartnerGraphDomainModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartnerGraph.Domain.Users.User", b =>
                {
                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid");

                    b.HasKey("ExternalId");

                    b.HasIndex("PartnerId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PartnerGraph.Domain.Users.User", b =>
                {
                    b.HasOne("PartnerGraph.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
