// <auto-generated />
using System;
using Commissions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Commissions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommissionsDbContext))]
    [Migration("20260923132425_AddCommissionsDomainModel")]
    partial class AddCommissionsDomainModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Commissions.Domain.CommissionSchemes.CommissionScheme", b =>
                {
                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Version"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("SchemaType")
                        .HasColumnType("smallint")
                        .HasComment("Possible values of enum type: CommissionSchemaType\n----------\n0 -- Linear\n1 -- Fibonacci\n");

                    b.HasKey("Version");

                    b.ToTable("CommissionsSchemes", (string)null);
                });

            modelBuilder.Entity("Commissions.Domain.Commissions.Commission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExternalEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("smallint")
                        .HasComment("Possible values of enum type: CommissionPaymentStatus\n----------\n0 -- Pending\n1 -- Paid\n");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalEventId");

                    b.HasIndex("SchemaVersion");

                    b.ToTable("Commissions", (string)null);
                });

            modelBuilder.Entity("Commissions.Domain.ProfitEvents.ProfitEvent", b =>
                {
                    b.Property<Guid>("ExternalEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OcurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProfitCents")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("SchemaType")
                        .HasColumnType("smallint")
                        .HasComment("Possible values of enum type: CommissionSchemaType\n----------\n0 -- Linear\n1 -- Fibonacci\n");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasComment("Possible values of enum type: ProfitEventStatus\n----------\n0 -- PendingCalculation\n1 -- Calculated\n2 -- Failed\n");

                    b.Property<Guid>("UserExternalId")
                        .HasColumnType("uuid");

                    b.HasKey("ExternalEventId");

                    b.ToTable("ProfitEvents", (string)null);
                });

            modelBuilder.Entity("Commissions.Domain.Commissions.Commission", b =>
                {
                    b.HasOne("Commissions.Domain.ProfitEvents.ProfitEvent", null)
                        .WithMany()
                        .HasForeignKey("ExternalEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Commissions.Domain.CommissionSchemes.CommissionScheme", null)
                        .WithMany()
                        .HasForeignKey("SchemaVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
