// <auto-generated />
using System;
using Commissions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Commissions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommissionsDbContext))]
    partial class CommissionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Commissions.Domain.CommissionSchemes.CommissionScheme", b =>
                {
                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Version"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("SchemaType")
                        .HasColumnType("smallint")
                        .HasComment("Possible values of enum type: CommissionSchemaType\n----------\n0 -- Linear\n1 -- Fibonacci\n");

                    b.HasKey("Version");

                    b.ToTable("CommissionsSchemes", (string)null);
                });

            modelBuilder.Entity("Commissions.Domain.Commissions.Commission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExternalEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("smallint")
                        .HasComment("Possible values of enum type: CommissionPaymentStatus\n----------\n0 -- Pending\n1 -- Paid\n");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchemaVersion");

                    b.HasIndex("ExternalEventId", "BeneficiaryId")
                        .IsUnique();

                    b.ToTable("Commissions", (string)null);
                });

            modelBuilder.Entity("Commissions.Domain.ProfitEvents.ProfitEvent", b =>
                {
                    b.Property<Guid>("ExternalEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CalculationAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("CalculationStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CalculationToken")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("NextCalculationAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OcurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProfitCents")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("SchemaType")
                        .HasColumnType("smallint")
                        .HasComment("Possible values of enum type: CommissionSchemaType\n----------\n0 -- Linear\n1 -- Fibonacci\n");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasComment("Possible values of enum type: ProfitEventStatus\n----------\n0 -- PendingCalculation\n1 -- Calculated\n2 -- Failed\n3 -- Calculating\n");

                    b.Property<Guid>("UserExternalId")
                        .HasColumnType("uuid");

                    b.HasKey("ExternalEventId");

                    b.HasIndex("Status", "CalculationStartedAt")
                        .HasDatabaseName("IX_ProfitEvents_StaleCalculation");

                    b.HasIndex("UserExternalId", "OcurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ProfitEvents_UserExternalId_OcurredAt");

                    b.HasIndex("Status", "NextCalculationAttemptAt", "ReceivedAt")
                        .HasDatabaseName("IX_ProfitEvents_PendingCalculation");

                    b.ToTable("ProfitEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProfitEvents_CalculationAttempts", "\"CalculationAttempts\" >= 0");
                        });
                });

            modelBuilder.Entity("Common.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageKey")
                        .HasColumnType("text")
                        .HasColumnName("message_key");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("trace_state");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_attempts", "attempts >= 0");
                        });
                });

            modelBuilder.Entity("Commissions.Domain.Commissions.Commission", b =>
                {
                    b.HasOne("Commissions.Domain.ProfitEvents.ProfitEvent", null)
                        .WithMany()
                        .HasForeignKey("ExternalEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Commissions.Domain.CommissionSchemes.CommissionScheme", null)
                        .WithMany()
                        .HasForeignKey("SchemaVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
